Updated nodejs version to LTS to avoid compatibility issues with npm
great-expectations/great_expectations_action pull request #80
Opened 2022-05-09 16:34 UTC by sravantit25

Fix for the below issue:
https://github.com/great-expectations/great_expectations_action/issues/79

Summary:
great_expectations_action build docker image is failing with incompatible Node.js version

2022-05-10 17:14 UTC, AFineDayFor requested changes
Howdy, the team raises a very strong point, which is can we just pin a version of node rather than have a remote script.

2022-05-11 17:07 UTC, sravantit25 commented
> Howdy, the team raises a very strong point, which is can we just pin a version of node rather than have a remote script.

The script points to the Long Term Supported version (LTS) which will automatically get upgraded to the next supported version when this version gets outdated. The link always remains updated. 
But if this is really a concern, I will update it to a specific version. Do let me know.

2022-06-01 05:20 UTC, sravantit25 commented
Hello! Can you let me know your thoughts on the above PR? I can make the change if required, submit for review and close it! 
Thank you!

2023-01-14 15:17 UTC, jcampbell approved these changes

2023-01-14 15:18 UTC, jcampbell commented
I'm going to merge this as-is, but also mark this action as explicitly no longer maintained. With changes to the underlying GX that have happened in the past couple of years, we recommend using checkpoints directly now!

2023-01-14 15:18 UTC, merged